#!/usr/bin/env node
/**
 * scripts/plot.js
 *
 * Reads scripts/history.json (generated by `make bench-history`) and emits
 * one SVG chart per metric into the same scripts/ directory:
 *
 *   overlapping_ns_per_op.svg
 *   overlapping_bytes_per_op.svg
 *   overlapping_allocs_per_op.svg
 *
 * Usage:
 *   node scripts/plot.js
 *   make bench-plot          ← same thing, via Makefile
 */

"use strict"

const fs   = require("fs")
const path = require("path")

// ─── Load history ─────────────────────────────────────────────────────────────

const histPath = path.join(__dirname, "history.json")
if (!fs.existsSync(histPath)) {
  console.error("scripts/history.json not found — run 'make bench-history' first")
  process.exit(1)
}

/** @type {History} */
const history = JSON.parse(fs.readFileSync(histPath, "utf8"))

if (!history.runs || history.runs.length === 0) {
  console.error("history.json has no runs — run 'make bench && make bench-history' first")
  process.exit(1)
}

// ─── Chart dimensions ─────────────────────────────────────────────────────────

const W         = 800   // total SVG width
const H         = 360   // total SVG height
const PAD_LEFT  = 88    // room for Y-axis labels
const PAD_RIGHT = 20
const PAD_TOP   = 44    // room for chart title
const PAD_BOT   = 72    // room for X-axis labels + legend

const CX1 = PAD_LEFT          // chart area: left edge
const CX2 = W - PAD_RIGHT     // chart area: right edge
const CY1 = PAD_TOP           // chart area: top edge
const CY2 = H - PAD_BOT       // chart area: bottom edge
const CW  = CX2 - CX1
const CH  = CY2 - CY1

// Colour palette — colourblind-friendly (Wong 2011)
const PALETTE = ["#e69f00", "#56b4e9", "#009e73", "#cc79a7"]

// Metrics to render
const METRICS = [
  { key: "ns_per_op",     label: "ns/op",         format: fmtNs     },
  { key: "bytes_per_op",  label: "Memory (B/op)",  format: fmtBytes  },
  { key: "allocs_per_op", label: "allocs/op",      format: fmtAllocs },
]

// ─── Formatting helpers ───────────────────────────────────────────────────────

function fmtNs(v) {
  if (v >= 1e9) return (v / 1e9).toPrecision(3) + " s"
  if (v >= 1e6) return (v / 1e6).toPrecision(3) + " ms"
  if (v >= 1e3) return (v / 1e3).toPrecision(3) + " µs"
  return v.toPrecision(3) + " ns"
}

function fmtBytes(v) {
  if (v >= 1024 * 1024) return (v / (1024 * 1024)).toPrecision(3) + " MB"
  if (v >= 1024)        return (v / 1024).toPrecision(3) + " KB"
  return v.toFixed(0) + " B"
}

function fmtAllocs(v) {
  if (v >= 1e6) return (v / 1e6).toPrecision(3) + "M"
  if (v >= 1e3) return (v / 1e3).toPrecision(3) + "k"
  return v.toFixed(0)
}

// ─── Scale helpers ────────────────────────────────────────────────────────────

function scaleX(i, n) {
  if (n <= 1) return CX1 + CW / 2
  return CX1 + (CW / (n - 1)) * i
}

function scaleY(v, lo, hi) {
  if (hi === lo) return CY2
  return CY2 - ((v - lo) / (hi - lo)) * CH
}

function autoRange(values) {
  const finite = values.filter(Number.isFinite)
  if (finite.length === 0) return { lo: 0, hi: 1 }
  let lo = Math.min(...finite)
  let hi = Math.max(...finite)
  const pad = (hi - lo) * 0.12 || Math.abs(hi) * 0.1 || 1
  lo = Math.max(0, lo - pad)
  hi = hi + pad
  return { lo, hi }
}

// ─── SVG building blocks ──────────────────────────────────────────────────────

function escXml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function renderGrid(lo, hi, yLabel, fmt) {
  const STEPS = 5
  const parts = []

  for (let i = 0; i < STEPS; i++) {
    const frac  = i / (STEPS - 1)
    const value = lo + (hi - lo) * frac
    const y     = scaleY(value, lo, hi).toFixed(2)
    const text  = escXml(fmt(value))

    parts.push(`
    <line x1="${CX1}" y1="${y}" x2="${CX2}" y2="${y}"
          stroke="#e5e7eb" stroke-dasharray="4 3" stroke-width="1"/>
    <text x="${CX1 - 6}" y="${(+y + 4).toFixed(2)}"
          text-anchor="end" font-size="11" fill="#9ca3af">${text}</text>`)
  }

  // Rotated Y-axis title
  const midY = ((CY1 + CY2) / 2).toFixed(2)
  parts.push(`
    <text x="13" y="${midY}" text-anchor="middle" font-size="11" fill="#6b7280"
          transform="rotate(-90 13 ${midY})">${escXml(yLabel)}</text>`)

  return parts.join("")
}

function renderXLabels() {
  const n = history.runs.length
  return history.runs.map((r, i) => {
    const x = scaleX(i, n).toFixed(2)
    return `
    <text x="${x}" y="${CY2 + 16}" text-anchor="end" font-size="10" fill="#6b7280"
          transform="rotate(-40 ${x} ${CY2 + 16})">${escXml(r.label)}</text>`
  }).join("")
}

function renderSeries(metricKey, lo, hi) {
  const n      = history.runs.length
  const series = history.series

  return series.map((s, si) => {
    const color  = PALETTE[si % PALETTE.length]
    const values = history.runs.map(r => (r[metricKey] && r[metricKey][s]) || 0)

    const dParts = values.map((v, i) =>
      `${i === 0 ? "M" : "L"} ${scaleX(i, n).toFixed(2)} ${scaleY(v, lo, hi).toFixed(2)}`
    )

    const dots = values.map((v, i) => {
      const x     = scaleX(i, n).toFixed(2)
      const y     = scaleY(v, lo, hi).toFixed(2)
      const label = history.runs[i].label
      return `      <circle cx="${x}" cy="${y}" r="4.5"
              fill="${color}" stroke="white" stroke-width="1.5">
        <title>${escXml(s)} @ ${escXml(label)}: ${escXml(v.toLocaleString())}</title>
      </circle>`
    }).join("\n")

    return `
    <!-- series: ${s} -->
    <path d="${dParts.join(" ")}"
          fill="none" stroke="${color}" stroke-width="2.5"
          stroke-linejoin="round" stroke-linecap="round"/>
${dots}`
  }).join("")
}

function renderLegend() {
  const series = history.series
  const itemW  = 170
  const n      = Math.min(series.length, 4)
  const startX = CX1 + (CW - n * itemW) / 2
  const baseY  = H - 20

  return series.map((s, i) => {
    const col  = i % 4
    const row  = Math.floor(i / 4)
    const x    = startX + col * itemW
    const y    = baseY - row * 18
    const fill = PALETTE[i % PALETTE.length]
    return `
    <rect x="${x}" y="${y - 9}" width="12" height="10" rx="2" fill="${fill}"/>
    <text x="${x + 16}" y="${y}" font-size="12" fill="#374151">${escXml(s)}</text>`
  }).join("")
}

// ─── Full chart SVG ───────────────────────────────────────────────────────────

function buildChart(metric) {
  const allValues = history.series.flatMap(s =>
    history.runs.map(r => (r[metric.key] && r[metric.key][s]) || 0)
  )
  const { lo, hi } = autoRange(allValues)

  const title = `${escXml(history.title)}  —  ${escXml(metric.label)}`

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">

  <style>
    text { font-family: ui-monospace, 'SFMono-Regular', Menlo, monospace; }
  </style>

  <!-- background -->
  <rect width="${W}" height="${H}" fill="#ffffff"/>

  <!-- chart title -->
  <text x="${CX1}" y="${CY1 - 14}"
        font-size="14" font-weight="600" fill="#111827">${title}</text>

  <!-- axes -->
  <line x1="${CX1}" y1="${CY1}" x2="${CX1}" y2="${CY2 + 1}"
        stroke="#9ca3af" stroke-width="1"/>
  <line x1="${CX1 - 1}" y1="${CY2}" x2="${CX2}" y2="${CY2}"
        stroke="#9ca3af" stroke-width="1"/>

  <!-- grid + Y labels -->
  ${renderGrid(lo, hi, metric.label, metric.format)}

  <!-- X labels -->
  ${renderXLabels()}

  <!-- data series -->
  ${renderSeries(metric.key, lo, hi)}

  <!-- legend -->
  ${renderLegend()}

</svg>
`
}

// ─── Generate all charts ──────────────────────────────────────────────────────

let generated = 0
for (const metric of METRICS) {
  const svg  = buildChart(metric)
  const file = `${history.topic}_${metric.key}.svg`
  const out  = path.join(__dirname, file)
  fs.writeFileSync(out, svg, "utf8")
  console.log(`  generated scripts/${file}`)
  generated++
}

console.log(`\nplot.js: ${generated} charts written to scripts/`)
